version: '3.8'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models_cache:/models_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - WHISPER_MODEL_ID=openai/whisper-large-v3
      - TRANSFORMERS_CACHE=/models_cache